name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches:
      - main   # Change if your default branch is "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo code
      - name: Checkout code
        uses: actions/checkout@v3

      # (Optional) If you have a Node.js app and need to build it
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build app
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build step"
          fi

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # change if you used a different region

      # Deploy to S3
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "iac/*" \
            --exclude "pipeline/*" \
            --acl public-read


      # Invalidate CloudFront cache
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
